// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elyrhwquavbptotxbizc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVseXJod3F1YXZicHRvdHhiaXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MDQ1MTIsImV4cCI6MjA4ODI4MDUxMn0.VtcoV5drg9lQ5pY4RIoZppBjfwE8-_tfVkDU_fUQ1bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});